import {
  useMemo,
  useState,
} from "react";


const TEXT = {
  tr: {
    eyebrow:
      "OLAY YÖNETİMİ",
    title:
      "Alarm Merkezi",
    subtitle:
      "GridGuard risk motoru tarafından üretilen operasyon alarmları.",
    open:
      "Açık",
    resolved:
      "Çözüldü",
    total:
      "Toplam",
    search:
      "Pano, risk veya mesaj ara...",
    all:
      "Tümü",
    status:
      "Durum",
    panel:
      "Pano",
    severity:
      "Seviye",
    risk:
      "Risk",
    primaryRisk:
      "Birincil Risk",
    message:
      "Mesaj",
    opened:
      "Açılış",
    resolvedAt:
      "Çözülme",
    empty:
      "Eşleşen alarm bulunamadı.",
    showing:
      "Gösterilen",
    of:
      "/",
    records:
      "alarm kaydı",
  },

  en: {
    eyebrow:
      "INCIDENT MANAGEMENT",
    title:
      "Alarm Center",
    subtitle:
      "Operational alerts generated by the GridGuard risk engine.",
    open:
      "Open",
    resolved:
      "Resolved",
    total:
      "Total",
    search:
      "Search panel, risk or message...",
    all:
      "All",
    status:
      "Status",
    panel:
      "Panel",
    severity:
      "Severity",
    risk:
      "Risk",
    primaryRisk:
      "Primary Risk",
    message:
      "Message",
    opened:
      "Opened",
    resolvedAt:
      "Resolved",
    empty:
      "No matching alarms found.",
    showing:
      "Showing",
    of:
      "of",
    records:
      "alarm records",
  },
};


const STATUS = {
  tr: {
    OPEN: "Açık",
    RESOLVED: "Çözüldü",
    UNKNOWN: "Bilinmiyor",
  },
  en: {
    OPEN: "Open",
    RESOLVED: "Resolved",
    UNKNOWN: "Unknown",
  },
};


const SEVERITY = {
  tr: {
    NORMAL: "Normal",
    WARNING: "Uyarı",
    HIGH: "Yüksek",
    CRITICAL: "Kritik",
    UNKNOWN: "Bilinmiyor",
  },
  en: {
    NORMAL: "Normal",
    WARNING: "Warning",
    HIGH: "High",
    CRITICAL: "Critical",
    UNKNOWN: "Unknown",
  },
};


const PRIMARY_RISK = {
  tr: {
    NONE: "Yok",
    THERMAL: "Termal",
    CURRENT: "Akım",
    OVERCURRENT: "Aşırı Akım",
    PARTIAL_DISCHARGE: "Kısmi Deşarj",
    ENVIRONMENT: "Çevresel",
    ARC_FLASH: "Ark Parlaması",
  },
  en: {
    NONE: "None",
    THERMAL: "Thermal",
    CURRENT: "Current",
    OVERCURRENT: "Overcurrent",
    PARTIAL_DISCHARGE: "Partial Discharge",
    ENVIRONMENT: "Environment",
    ARC_FLASH: "Arc Flash",
  },
};


function mapLabel(
  map,
  language,
  value
) {
  const key =
    String(
      value ?? "UNKNOWN"
    ).toUpperCase();

  return (
    map[language]?.[key] ??
    String(
      value ?? "--"
    ).replaceAll(
      "_",
      " "
    )
  );
}


const ALARM_MESSAGE_REPLACEMENTS_TR = [
  ["No telemetry data available.", "Telemetri verisi bulunmuyor."],
  ["Arc flash event detected.", "Ark parlaması olayı algılandı."],
  ["Immediate operator attention required.", "Acil operatör müdahalesi gerekiyor."],
  ["Current increased more than 35% above recent baseline.", "Akım, yakın dönem referans değerini %35'ten fazla aştı."],
  ["Current increased more than 20% above recent baseline.", "Akım, yakın dönem referans değerini %20'den fazla aştı."],
  ["Current is rising above recent baseline.", "Akım, yakın dönem referans değerinin üzerine çıkıyor."],
  ["Cable temperature is extremely high.", "Kablo sıcaklığı son derece yüksek."],
  ["Cable temperature is critically elevated.", "Kablo sıcaklığı kritik düzeyde yükselmiş."],
  ["Cable temperature is elevated.", "Kablo sıcaklığı yükselmiş."],
  ["Cable-to-ambient thermal delta is very high.", "Kablo ile ortam arasındaki sıcaklık farkı çok yüksek."],
  ["Abnormal cable-to-ambient thermal delta detected.", "Kablo ile ortam arasında anormal sıcaklık farkı algılandı."],
  ["Cable temperature is rising rapidly while ambient temperature remains relatively stable.", "Ortam sıcaklığı görece kararlı kalırken kablo sıcaklığı hızla yükseliyor."],
  ["Very high humidity detected.", "Çok yüksek nem algılandı."],
  ["High humidity detected.", "Yüksek nem algılandı."],
  ["Partial discharge activity is very high.", "Kısmi deşarj etkinliği çok yüksek."],
  ["Elevated partial discharge activity detected.", "Yükselmiş kısmi deşarj etkinliği algılandı."],
  ["Partial discharge activity is above normal range.", "Kısmi deşarj etkinliği normal aralığın üzerinde."],
  ["Partial discharge activity shows a strong rising trend.", "Kısmi deşarj etkinliği güçlü bir yükseliş eğilimi gösteriyor."],
  ["Partial discharge activity is increasing over time.", "Kısmi deşarj etkinliği zaman içinde artıyor."],
  ["Severe thermal escalation pattern detected.", "Şiddetli termal yükseliş örüntüsü algılandı."],
  ["Rising partial discharge pattern detected.", "Yükselen kısmi deşarj örüntüsü algılandı."],
  ["Severe partial discharge escalation pattern detected.", "Şiddetli kısmi deşarj yükseliş örüntüsü algılandı."],
  ["No significant anomaly detected.", "Belirgin bir anomali algılanmadı."],
  ["No strong signals are currently present.", "Şu anda güçlü bir risk sinyali bulunmuyor."],
  ["Deterministic risk is critical and has priority over AI advisory output.", "Deterministik risk kritiktir ve AI danışman çıktısına göre önceliklidir."],
  ["AI output is advisory and does not replace deterministic protection logic.", "AI çıktısı danışman niteliktedir ve deterministik koruma mantığının yerini almaz."],
  ["Insufficient trusted telemetry history for AI analysis.", "AI analizi için yeterli güvenilir telemetri geçmişi bulunmuyor."],
  ["Unusual behavior detected without confirmed future escalation.", "Gelecekte kesin bir risk artışı doğrulanmadan olağandışı davranış algılandı."],
  ["ML models are trained on synthetic prototype telemetry and require field calibration before production use.", "Makine öğrenmesi modelleri sentetik prototip telemetrisiyle eğitilmiştir; gerçek kullanım öncesinde saha kalibrasyonu gerekir."],
  ["Unusual behavior detected.", "Olağandışı davranış algılandı."],
  ["No unusual behavior detected.", "Olağandışı davranış algılanmadı."],
];


function translateAlarmMessage(
  value,
  language
) {
  if (!value) {
    return "--";
  }

  if (
    language !== "tr"
  ) {
    return value;
  }

  let translated =
    String(value);

  for (
    const [
      source,
      target,
    ] of ALARM_MESSAGE_REPLACEMENTS_TR
  ) {
    translated =
      translated.replaceAll(
        source,
        target
      );
  }

  return translated;
}


function formatDateTime(
  value,
  language
) {
  if (!value) {
    return "--";
  }

  return new Date(
    value
  ).toLocaleString(
    language === "tr"
      ? "tr-TR"
      : "en-GB",
    {
      day: "2-digit",
      month: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    }
  );
}


function AlarmCenter({
  alarms = [],
  onOpenPanel,
  language = "tr",
}) {
  const safeLanguage =
    language === "en"
      ? "en"
      : "tr";

  const t =
    TEXT[safeLanguage];

  const [
    statusFilter,
    setStatusFilter,
  ] = useState("ALL");

  const [search, setSearch] =
    useState("");


  const openCount = useMemo(
    () =>
      alarms.filter(
        (alarm) =>
          alarm.status ===
          "OPEN"
      ).length,
    [alarms]
  );


  const resolvedCount =
    useMemo(
      () =>
        alarms.filter(
          (alarm) =>
            alarm.status ===
            "RESOLVED"
        ).length,
      [alarms]
    );


  const filteredAlarms =
    useMemo(() => {
      const searchValue =
        search
          .trim()
          .toLowerCase();

      return [...alarms]
        .filter((alarm) => {
          const matchesStatus =
            statusFilter ===
              "ALL" ||
            alarm.status ===
              statusFilter;

          const matchesSearch =
            !searchValue ||
            alarm.panel_id
              ?.toLowerCase()
              .includes(
                searchValue
              ) ||
            alarm.primary_risk
              ?.toLowerCase()
              .includes(
                searchValue
              ) ||
            alarm.message
              ?.toLowerCase()
              .includes(
                searchValue
              );

          return (
            matchesStatus &&
            matchesSearch
          );
        })
        .sort((a, b) => {
          const aTime =
            new Date(
              a.opened_at ??
              0
            ).getTime();

          const bTime =
            new Date(
              b.opened_at ??
              0
            ).getTime();

          return (
            bTime - aTime
          );
        });
    }, [
      alarms,
      statusFilter,
      search,
    ]);


  return (
    <section className="alarm-center">

      <div className="alarm-center-heading">

        <div>
          <p className="eyebrow">
            {t.eyebrow}
          </p>

          <h3>
            {t.title}
          </h3>

          <p>
            {t.subtitle}
          </p>
        </div>


        <div className="alarm-summary-strip">

          <div className="alarm-summary-item">
            <span>
              {t.open}
            </span>

            <strong className="alarm-open-number">
              {openCount}
            </strong>
          </div>


          <div className="alarm-summary-item">
            <span>
              {t.resolved}
            </span>

            <strong className="alarm-resolved-number">
              {resolvedCount}
            </strong>
          </div>


          <div className="alarm-summary-item">
            <span>
              {t.total}
            </span>

            <strong>
              {alarms.length}
            </strong>
          </div>

        </div>

      </div>


      <div className="alarm-controls">

        <input
          type="text"
          placeholder={
            t.search
          }
          value={search}
          onChange={(event) =>
            setSearch(
              event.target.value
            )
          }
        />


        <div className="alarm-filter-tabs">

          {[
            ["ALL", t.all],
            ["OPEN", t.open],
            [
              "RESOLVED",
              t.resolved,
            ],
          ].map(
            ([
              key,
              label,
            ]) => (
              <button
                type="button"
                className={
                  statusFilter ===
                  key
                    ? "active"
                    : ""
                }
                onClick={() =>
                  setStatusFilter(
                    key
                  )
                }
                key={key}
              >
                {label}
              </button>
            )
          )}

        </div>

      </div>


      <div className="alarm-table-wrapper">

        <table className="alarm-table">

          <thead>
            <tr>
              <th>
                {t.status}
              </th>
              <th>
                {t.panel}
              </th>
              <th>
                {t.severity}
              </th>
              <th>
                {t.risk}
              </th>
              <th>
                {t.primaryRisk}
              </th>
              <th>
                {t.message}
              </th>
              <th>
                {t.opened}
              </th>
              <th>
                {t.resolvedAt}
              </th>
            </tr>
          </thead>


          <tbody>

            {filteredAlarms.length ===
            0 ? (

              <tr>
                <td
                  colSpan="8"
                  className="alarm-empty-cell"
                >
                  {t.empty}
                </td>
              </tr>

            ) : (

              filteredAlarms.map(
                (alarm) => (

                  <tr
                    key={alarm.id}
                    className={
                      alarm.status ===
                      "OPEN"
                        ? "open-alarm-row"
                        : ""
                    }
                  >

                    <td>
                      <span
                        className={`alarm-status-badge ${
                          (
                            alarm.status ??
                            "unknown"
                          ).toLowerCase()
                        }`}
                      >
                        {mapLabel(
                          STATUS,
                          safeLanguage,
                          alarm.status
                        )}
                      </span>
                    </td>


                    <td>
                      <button
                        type="button"
                        className="alarm-panel-button"
                        onClick={() =>
                          onOpenPanel(
                            alarm.panel_id
                          )
                        }
                      >
                        {
                          alarm.panel_id
                        }
                      </button>
                    </td>


                    <td>
                      <span
                        className={`alarm-severity-badge ${
                          (
                            alarm.severity ??
                            "unknown"
                          ).toLowerCase()
                        }`}
                      >
                        {mapLabel(
                          SEVERITY,
                          safeLanguage,
                          alarm.severity
                        )}
                      </span>
                    </td>


                    <td className="alarm-risk-score">
                      {
                        alarm.risk_score ??
                        0
                      }
                    </td>


                    <td>
                      {mapLabel(
                        PRIMARY_RISK,
                        safeLanguage,
                        alarm.primary_risk
                      )}
                    </td>


                    <td className="alarm-message-cell">
                      {translateAlarmMessage(
                        alarm.message,
                        safeLanguage
                      )}
                    </td>


                    <td>
                      {formatDateTime(
                        alarm.opened_at,
                        safeLanguage
                      )}
                    </td>


                    <td>
                      {alarm.status ===
                      "RESOLVED"
                        ? formatDateTime(
                            alarm.resolved_at,
                            safeLanguage
                          )
                        : "--"}
                    </td>

                  </tr>

                )
              )

            )}

          </tbody>

        </table>

      </div>


      <div className="alarm-center-footer">
        {t.showing}

        <strong>
          {
            filteredAlarms.length
          }
        </strong>

        {t.of}

        <strong>
          {alarms.length}
        </strong>

        {t.records}
      </div>

    </section>
  );
}


export default AlarmCenter;
